import { useEffect, useState } from 'react';
import { analyticsService, type TelemetrySession } from './analyticsService';
import { isDemoMode } from '../../config/environment';
import { Empty, Icon, PageHeading } from '../shared/ui';
import { downloadJson } from '../shared/format';
import { useWorkspace } from '../content/workspaceContext';
function percent(value: number, total: number) { return total ? (100 * value / total).toFixed(1) + '%' : '—'; }
function mean(values: number[], digits = 1) { return values.length ? (values.reduce((a, b) => a + b, 0) / values.length).toFixed(digits) : '—'; }
export function InternalAnalyticsPage() {
  const { state } = useWorkspace();
  const [days, setDays] = useState(7), [version, setVersion] = useState('all');
  const [sessions, setSessions] = useState<TelemetrySession[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const [retry, setRetry] = useState(0), [mapFilter, setMapFilter] = useState('all');
  useEffect(() => {
    let active = true;
    analyticsService.load(days, version).then(data => { if (active) { setSessions(data); setError(''); } })
      .catch(e => { if (active) setError(e instanceof Error ? e.message : 'Could not load telemetry.'); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [days, version, retry]);
  const data = sessions.filter(s => mapFilter === 'all' || s.map === mapFilter);
  const maps = [...new Set(sessions.map(s => s.map))], weapons = [...new Set(data.map(s => s.weapon))];
  const solvers = [...new Set(data.map(s => s.solver))], versions = [...new Set([...state.releases.map(r => r.version), ...sessions.map(s => s.contentVersion)])];
  return <div className="sv-page"><PageHeading eyebrow="TELEMETRY & RESEARCH" title="Player analytics" description="Understand difficulty, player progression and squad coordination by content version." action={<button className="sv-button" disabled={loading || !!error || !data.length} onClick={() => downloadJson(data, 'shadowvale-telemetry-' + days + 'd.json')}><Icon name="download" />Export data</button>} />
    {isDemoMode && <div className="sv-alert">Synthetic demo telemetry · these examples illustrate the dashboard and do not represent player measurements or research results.</div>}
    <div className="sv-analytics-filters sv-form"><div className="sv-segmented">{[7, 30].map(d => <button className={days === d ? 'is-active' : ''} key={d} onClick={() => { if (d !== days) { setLoading(true); setDays(d); } }}>{d} days</button>)}</div><label>Content version<select value={version} onChange={e => { setLoading(true); setVersion(e.target.value); setMapFilter('all'); }}><option value="all">All versions</option>{[...new Set([...versions, ...(isDemoMode ? ['1.0.0', '1.1.0'] : []), ...(version === 'all' ? [] : [version])])].map(v => <option key={v} value={v}>v{v}</option>)}</select></label><label>Map<select value={mapFilter} onChange={e => setMapFilter(e.target.value)}><option value="all">All maps</option>{maps.map(m => <option key={m}>{m}</option>)}</select></label></div>
    {loading ? <div className="portal-state" role="status">Loading telemetry…</div> : error ? <div className="sv-alert sv-alert-error" role="alert">{error}<button className="sv-button" onClick={() => { setLoading(true); setRetry(retry + 1); }}>Try again</button></div> : !data.length ? <Empty title="No telemetry in this selection" description="Try a different date range, content version or map." /> : <>
      <div className="sv-stats-grid">{[{ label: 'Sessions', value: data.length, detail: 'Anonymized session events' }, { label: 'Mission completion', value: percent(data.filter(s => s.completed).length, data.length), detail: 'Completed / started sessions' }, { label: 'Capture rate', value: percent(data.filter(s => s.captured).length, data.length), detail: 'Sessions captured by enemy squads' }, { label: 'Stealth playstyle', value: percent(data.filter(s => s.stealth).length, data.length), detail: 'Stealth / all sessions' }].map(s => <article className="sv-stat" key={s.label}><span>{s.label}</span><strong>{s.value}</strong><small>{s.detail}</small></article>)}</div>
      <div className="sv-dashboard-columns"><section className="sv-panel"><div className="sv-panel-heading"><div><h2>Mission completion</h2><p>Completion rate and sample size by map.</p></div></div><div className="sv-bars">{[...new Set(data.map(s => s.map))].map(m => { const rows = data.filter(s => s.map === m), rate = 100 * rows.filter(s => s.completed).length / rows.length; return <div key={m}><div><strong>{m}</strong><span>{rate.toFixed(0)}% · n={rows.length}</span></div><div className="sv-bar-track"><span style={{ width: rate + '%' }} /></div></div>; })}</div></section>
        <section className="sv-panel"><div className="sv-panel-heading"><div><h2>Weapon usage</h2><p>Primary weapon used per session.</p></div></div><div className="sv-bars">{weapons.map(w => { const count = data.filter(s => s.weapon === w).length; return <div key={w}><div><strong>{w}</strong><span>{percent(count, data.length)}</span></div><div className="sv-bar-track"><span style={{ width: (100 * count / data.length) + '%' }} /></div></div>; })}</div></section></div>
      <section className="sv-panel"><div className="sv-panel-heading"><div><span className="sv-eyebrow">CLASSICAL vs QUANTUM-INSPIRED</span><h2>AI method comparison</h2><p>Compare cohorts at the selected content version. Matched compute budgets and seeds must be controlled by the experiment.</p></div><Icon name="neurology" /></div><div className="sv-table-wrap"><table className="sv-table"><thead><tr><th>Solver</th><th>Sessions</th><th>Capture rate</th><th>Escape time (s)</th><th>Coordination score</th><th>Latency p95 (ms)</th></tr></thead><tbody>{solvers.map(solver => {
        const rows = data.filter(s => s.solver === solver), latencies = rows.map(s => s.latencyMs).sort((a, b) => a - b);
        return <tr key={solver}><td><strong className="sv-mono">{solver.toUpperCase()}</strong><small>{['greedy', 'ga', 'sa'].includes(solver) ? 'Classical baseline' : 'Quantum-inspired / simulator'}</small></td><td>{rows.length}</td><td>{percent(rows.filter(s => s.captured).length, rows.length)}</td><td>{mean(rows.filter(s => !s.captured).map(s => s.escapeSeconds))}</td><td>{mean(rows.map(s => s.coordinationScore), 2)}</td><td>{latencies[Math.ceil(latencies.length * .95) - 1]}</td></tr>;
      })}</tbody></table></div><p className="sv-table-note">Escape time is averaged over uncaptured sessions. Coordination scores use a 0–1 scale; cohorts are descriptive, without a significance claim.</p></section>
      <div className="sv-dashboard-columns"><section className="sv-panel"><div className="sv-panel-heading"><div><h2>Difficulty heatmap</h2><p>{mapFilter === 'all' ? 'Select one map to inspect spatial difficulty.' : 'Player deaths per normalized map cell.'}</p></div></div>{mapFilter === 'all' ? <Empty title="Select a map" description="Spatial events are displayed for one map at a time." /> : <div className="sv-heatmap-area"><div className="sv-heatmap" aria-label="Player death heatmap">{Array.from({ length: 48 }, (_, i) => { const count = data.flatMap(s => s.deaths).filter(d => d.x === i % 8 && d.y === Math.floor(i / 8)).length; return <div key={i} title={`Cell (${i % 8}, ${Math.floor(i / 8)}): ${count} deaths`} style={{ backgroundColor: count ? `rgba(249, 149, 90, ${Math.min(.95, .25 + count * .18)})` : '#202931' }}>{count || '·'}</div>; })}</div><small>0 deaths <span className="sv-heat-legend" /> More deaths</small></div>}</section>
        <section className="sv-panel"><div className="sv-panel-heading"><div><h2>Skill progression</h2><p>Average recorded skill level per session.</p></div></div><div className="sv-bars">{(['shooting', 'engineering', 'stealth'] as const).map(skill => { const values = data.filter(s => s.skill === skill).map(s => s.skillLevel); return <div key={skill}><div><strong>{skill}</strong><span>Level {mean(values)} · n={values.length}</span></div><div className="sv-bar-track"><span style={{ width: (Number(mean(values)) / 5 * 100 || 0) + '%' }} /></div></div>; })}</div></section></div>
    </>}
  </div>;
}
