import { useTranslation } from '../preferences/preferencesContext';
import { useEffect, useState } from 'react';
import { useAuth } from '../../hooks/useAuth';
import { can } from '../auth/access';
import { analyticsApi } from './analyticsApi';
import { solverSpecs,defaultWeights } from './solverSpecs';
import type { SolverConfigurationDto,EnumsDto,JsonValue } from '../../services/api/contracts';
import { errorMessage } from '../../services/api/errors';
import { Empty, Icon, Status } from '../shared/ui';
import { NumericControl } from '../shared/NumericControl';
type Form={mode:'create'|'edit'|'clone';row?:SolverConfigurationDto;code:string;name:string;algorithm:string;library:string;budget:number;params:Record<string,JsonValue>;weights:Record<string,JsonValue>};
function asObject(value:JsonValue):Record<string,JsonValue>{return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}
export function SolverConfigurations({enums}:{enums?:EnumsDto}){
  const t = useTranslation();
 const {user}=useAuth(),canManage=!!user&&can(user.role,'solverEdit');
 const [rows,setRows]=useState<SolverConfigurationDto[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[form,setForm]=useState<Form|null>(null);
 const [inputErrors,setInputErrors]=useState<Record<string,string>>({});
 const [family,setFamily]=useState(''),[algorithm,setAlgorithm]=useState(''),[active,setActive]=useState('all');
 useEffect(()=>{let live=true;analyticsApi.solvers().then(r=>{if(live){setRows(r);setLoading(false);setError('');}}).catch(e=>{if(live){setError(errorMessage(e));setLoading(false);}});return()=>{live=false;};},[retry]);
 function patch(value:Partial<Form>){setForm(f=>f?{...f,...value}:f);}
 function report(key:string,value:string){setInputErrors(e=>({...e,[key]:value}));}
 async function edit(row:SolverConfigurationDto,mode:'edit'|'clone'){
  setBusy(true);setError('');try{const current=await analyticsApi.solver(row.id);setInputErrors({});setForm({mode,row:current,code:mode==='clone'?current.code+'_copy':current.code,name:mode==='clone'?current.name+' copy':current.name,algorithm:current.algorithm,library:current.library||'',budget:Number(current.timeBudgetMs),params:asObject(current.params),weights:asObject(current.quboWeights)});}catch(e){setError(errorMessage(e));}finally{setBusy(false);}
 }
 const used=!!form?.row&&(Number(form.row.sessionCount)>0||Number(form.row.resultCount)>0);
 const frozen=form?.mode==='clone'||form?.mode==='edit'&&used;
 async function save(e:React.FormEvent){
  e.preventDefault();if(!form)return;setBusy(true);setError('');
  try{
   if(form.mode==='clone'){const clone=await analyticsApi.clone(form.row!.id,form.code,form.name);setForm({mode:'edit',row:clone,code:clone.code,name:clone.name,algorithm:clone.algorithm,library:clone.library||'',budget:Number(clone.timeBudgetMs),params:asObject(clone.params),weights:asObject(clone.quboWeights)});}
   else {const data={name:form.name,library:form.library||null,timeBudgetMs:form.budget,params:form.params,quboWeights:form.weights};if(form.mode==='create')await analyticsApi.create({...data,code:form.code,algorithm:form.algorithm});else await analyticsApi.update(form.row!.id,data);setForm(null);}
   setRetry(retry+1);
  }catch(e){setError(errorMessage(e));}finally{setBusy(false);}
 }
 async function toggle(row:SolverConfigurationDto){setBusy(true);setError('');try{await analyticsApi.active(row.id,!row.isActive);setRetry(retry+1);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function remove(row:SolverConfigurationDto){if(!window.confirm('Delete unused configuration '+row.code+'?'))return;setBusy(true);setError('');try{await analyticsApi.remove(row.id);setRetry(retry+1);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 const visible=rows.filter(r=>(!family||r.family===family)&&(!algorithm||r.algorithm===algorithm)&&(active==='all'||r.isActive===(active==='active')));
 return <><section className="sv-panel"><div className="sv-panel-heading"><h2>{t("Solver configurations")}</h2><div className="sv-row-actions"><button className="sv-button" disabled={busy} onClick={()=>{setLoading(true);setRetry(retry+1);}}>{t("Refresh")}</button>{canManage&&<button className="sv-button sv-button-primary" disabled={busy||!enums} onClick={()=>{setError('');setInputErrors({});setForm({mode:'create',code:'',name:'',algorithm:enums!.solverAlgorithms[0],library:'',budget:250,params:{},weights:{...defaultWeights}});}}><Icon name="add"/>{t("New configuration")}</button>}</div></div>
 <div className="sv-analytics-filters sv-form"><label>{t("Family")}<select value={family} onChange={e=>setFamily(e.target.value)}><option value="">{t("All families")}</option>{enums?.solverFamilies.map(v=><option key={v}>{v}</option>)}</select></label><label>{t("Algorithm")}<select value={algorithm} onChange={e=>setAlgorithm(e.target.value)}><option value="">{t("All algorithms")}</option>{enums?.solverAlgorithms.map(v=><option key={v}>{v}</option>)}</select></label><label>{t("Status")}<select value={active} onChange={e=>setActive(e.target.value)}><option value="all">{t("All")}</option><option value="active">{t("Active")}</option><option value="inactive">{t("Inactive")}</option></select></label></div>
 {error&&!form&&<div className="sv-alert sv-alert-error" role="alert" style={{whiteSpace:'pre-wrap'}}>{error}<button className="sv-button" onClick={()=>setRetry(retry+1)}>{t("Retry")}</button></div>}
 {loading?<div role="status" className="sv-empty">{t("Loading configurations…")}</div>:<div className="sv-table-wrap"><table className="sv-table"><thead><tr>{['Configuration','Algorithm / family','Budget','Usage','Status','Actions'].map(h=><th key={h}>{t(h)}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.code} · {r.variant}</small></td><td>{r.algorithm}<small>{r.family}</small></td><td>{r.timeBudgetMs} {t("ms")}</td><td>{r.sessionCount} {t("sessions ·")} {r.resultCount} {t("results")}</td><td><Status value={r.isActive?'active':'inactive'}/><small>{t(r.isAbArm?'Human A/B arm':'Outside human A/B')}</small></td><td><div className="sv-row-actions"><button className="sv-button sv-button-small" disabled={busy} onClick={()=>void edit(r,'edit')}>{canManage?t("Edit"):t("View")}</button>{canManage&&<><button className="sv-button sv-button-small" disabled={busy} onClick={()=>void edit(r,'clone')}>{t("Clone")}</button><button className="sv-button sv-button-small" disabled={busy} onClick={()=>void toggle(r)}>{r.isActive?t("Deactivate"):t("Activate")}</button><button className="sv-button sv-button-small" disabled={busy||Number(r.sessionCount)>0||Number(r.resultCount)>0} onClick={()=>void remove(r)}>{t("Delete")}</button></>}</div></td></tr>)}</tbody></table>{!visible.length&&<Empty title={t("No configurations")}/>}</div>}<p className="sv-table-note">{t("New and cloned configurations start inactive. Active configurations must share time budget and all six QUBO weights. Quantum hardware is excluded from human A/B assignment.")}</p></section>
 {form&&<div className="sv-modal-backdrop"><section className="sv-modal sv-solver-modal" role="dialog" aria-modal="true" aria-label={t("Solver configuration")} style={{maxHeight:'90vh',overflowY:'auto',width:'min(840px,95vw)'}} onKeyDown={e=>{if(e.key==='Escape'&&!busy)setForm(null);}}><h2>{!canManage?t("View"):form.mode==='clone'?t("Clone"):form.mode==='create'?t("New"):t("Edit")} {t("configuration")}</h2>{used&&form.mode==='edit'&&<div className="sv-alert">{t("This configuration has recorded sessions/results. Only its name can change; clone it to tune parameters.")}</div>}
 <form className="sv-form" onSubmit={save}><fieldset disabled={busy||!canManage} style={{border:0,padding:0}}><div className="sv-field-grid"><label>{t("Code")}<input autoFocus required maxLength={64} pattern="^[a-z][a-z0-9_]*$" disabled={form.mode==='edit'} value={form.code} onChange={e=>patch({code:e.target.value})}/></label><label>{t("Name")}<input required maxLength={100} value={form.name} onChange={e=>patch({name:e.target.value})}/></label><label>{t("Algorithm")}<select disabled={form.mode!=='create'} value={form.algorithm} onChange={e=>{patch({algorithm:e.target.value,params:{}});setInputErrors({});}}>{enums?.solverAlgorithms.map(v=><option key={v}>{v}</option>)}</select></label><label>{t("Library")}<input maxLength={50} disabled={frozen} value={form.library} onChange={e=>patch({library:e.target.value})}/></label><NumericControl label={t("Time budget")} value={form.budget} min={1} max={10000} step={1} sliderMin={1} sliderMax={1000} unit="ms" disabled={frozen} onChange={v=>patch({budget:v!})} onError={e=>report('budget',e)}/></div>
 <h3>{t("Algorithm parameters")}</h3><div className="sv-field-grid">{Object.entries(solverSpecs[form.algorithm]||{}).map(([key,spec])=>spec.options?<label key={key}>{key}<select disabled={frozen} value={String(form.params[key]||'')} onChange={e=>{const params={...form.params};if(e.target.value)params[key]=e.target.value;else delete params[key];patch({params});}}><option value="">{t("Default")}</option>{spec.options.map(v=><option key={v}>{v}</option>)}</select></label>:<NumericControl key={form.algorithm+key} label={key} value={form.params[key]==null?null:Number(form.params[key])} nullable min={spec.min} max={spec.max} step={spec.step} sliderMin={spec.min} sliderMax={Math.min(spec.max,Math.max(spec.min+1,100))} disabled={frozen} onChange={v=>{const params={...form.params};if(v===null)delete params[key];else params[key]=v;patch({params});}} onError={e=>report(key,e)}/>)}</div>{!Object.keys(solverSpecs[form.algorithm]||{}).length&&<p>{t("No configurable parameters for this algorithm.")}</p>}
 <h3>{t("QUBO weights")}</h3><div className="sv-field-grid">{Object.keys(defaultWeights).map(key=><NumericControl key={key} label={key.replace('weight_','').replace('penalty_','Penalty ')} value={Number(form.weights[key]??defaultWeights[key])} min={0} max={1000} step={0.000001} sliderMin={0} sliderMax={10} disabled={frozen} onChange={v=>patch({weights:{...form.weights,[key]:v!}})} onError={e=>report(key,e)}/>)}</div>
 {error&&<div className="sv-alert sv-alert-error" role="alert" style={{whiteSpace:'pre-wrap'}}>{error}</div>}{canManage&&<div className="sv-row-actions"><button type="button" className="sv-button" onClick={()=>setForm(null)}>{t("Cancel")}</button><button className="sv-button sv-button-primary" disabled={!form.name.trim()||!form.code.trim()||Object.values(inputErrors).some(Boolean)}>{busy?t("Saving…"):form.mode==='clone'?t("Create inactive clone"):t("Save configuration")}</button></div>}</fieldset></form>{!canManage&&<button className="sv-button" onClick={()=>setForm(null)}>{t("Close")}</button>}</section></div>}
 </>;
}
