using System;
using System.Collections.Generic;

namespace ShadowVale.Contracts.Game
{
    // POST /api/game/sessions, sent when play starts. Calling it again with the same SessionId returns the same answer.
    public class StartSessionRequest
    {
        // Generated by the game for every session (random GUID)
        public Guid SessionId { get; set; }

        // Random GUID generated once per install and kept on disk; no personal data
        public Guid InstallId { get; set; }

        // "human" (normal play) or "replay" (benchmark harness)
        public string Source { get; set; } = "human";

        // Replay only (required there): code of the solver configuration to run. Human sessions must leave it null:
        // the server assigns their solver (A/B test).
        public string? RequestedVariant { get; set; }

        // Content version the game is playing; null when it runs on its built-in fallback bundle
        public Guid? ContentVersionId { get; set; }

        public string? MapCode { get; set; }
        public string? ClientVersion { get; set; }
        public string Platform { get; set; } = "";
        public DateTimeOffset StartedAt { get; set; }
    }

    public class StartSessionResponse
    {
        // Null when no solver is assigned: the game then uses the default from its content bundle,
        // and the session is left out of the solver comparison
        public AssignedSolver? Solver { get; set; }
    }

    // Solver the game must use for every squad re-plan of this session
    public class AssignedSolver
    {
        public Guid ConfigurationId { get; set; }
        public string Code { get; set; } = "";

        // Solver id for the sidecar's /solve (greedy, ga, sa, sqa, qiea, qaoa)
        public string Variant { get; set; } = "";

        // Hyper-parameters to pass to /solve as is
        public Dictionary<string, object?> Params { get; set; } = new Dictionary<string, object?>();

        // weight_coverage, weight_redundancy, weight_flanking, weight_cover, weight_distance, penalty_conflict
        public Dictionary<string, double> QuboWeights { get; set; } = new Dictionary<string, double>();
        public int TimeBudgetMs { get; set; }
    }
}
