using System;
using System.Collections.Generic;

namespace ShadowVale.Contracts.Telemetry
{
    // PUT /api/game/sessions/{sessionId}, sent once when the session ends. Safe to resend: items already stored are
    // counted as duplicates. Status codes for the game: 2xx and 409 = done; 400 / 413 = drop the batch; anything else = retry later.
    public class SessionUpload
    {
        public Guid InstallId { get; set; }

        // "human" or "replay", same as when the session was started
        public string Source { get; set; } = "human";
        public Guid? ContentVersionId { get; set; }
        public string? MapCode { get; set; }
        public string? ClientVersion { get; set; }
        public string Platform { get; set; } = "";
        public DateTimeOffset StartedAt { get; set; }
        public DateTimeOffset EndedAt { get; set; }

        // Completed, Died, Quit or Crashed
        public string Outcome { get; set; } = "";

        public SessionStats? Stats { get; set; }
        public List<TelemetryEventDto> Events { get; set; } = new List<TelemetryEventDto>();
        public List<CoordinationResultDto> CoordinationResults { get; set; } = new List<CoordinationResultDto>();
    }

    // Counters kept by the game for the whole session. They stay exact even though events are throttled and capped,
    // so analytics reads these instead of counting events.
    public class SessionStats
    {
        // Event type -> number of times it happened (including events not sent)
        public Dictionary<string, int> EventCounts { get; set; } = new Dictionary<string, int>();

        // Weapon code -> shots fired / kills made with it
        public Dictionary<string, int> ShotsByWeapon { get; set; } = new Dictionary<string, int>();
        public Dictionary<string, int> KillsByWeapon { get; set; } = new Dictionary<string, int>();

        // Silent kills vs kills with a weapon: the stealth-vs-combat ratio is Takedowns / (Takedowns + WeaponKills)
        public int Takedowns { get; set; }
        public int WeaponKills { get; set; }
        public int TimesDetected { get; set; }

        // Events the game could not send (cap / queue full)
        public int EventsDropped { get; set; }

        // Every encounter, including those without any re-plan: capture rate and escape time come from here
        public List<EncounterStats> Encounters { get; set; } = new List<EncounterStats>();
    }

    // One encounter: a squad engages the player until the player is captured, escapes or eliminates the squad
    public class EncounterStats
    {
        // 0, 1, 2... in the order they started
        public int Index { get; set; }

        // PlayerCaptured, PlayerEscaped, SquadEliminated or Aborted (session ended mid-encounter)
        public string Outcome { get; set; } = "";
        public DateTimeOffset StartedAt { get; set; }
        public DateTimeOffset EndedAt { get; set; }
        public int NumAgents { get; set; }
        public int NumReplans { get; set; }
        public int NumFallbacks { get; set; }
        public double? CoordinationScore { get; set; }
    }

    public class TelemetryEventDto
    {
        // Generated by the game; a resent event with the same id is ignored
        public Guid ClientEventId { get; set; }

        // One of TelemetryEventTypes
        public string EventType { get; set; } = "";
        public DateTimeOffset OccurredAt { get; set; }

        // Defaults to the session's map
        public string? MapCode { get; set; }

        // Player / event position: world X and world Z (the ground plane) in metres
        public float? PosX { get; set; }
        public float? PosY { get; set; }

        // Type-specific fields, at most 4 KB once serialized (see TelemetryEventTypes)
        public Dictionary<string, object?>? Payload { get; set; }
    }

    // One squad re-plan solved as a QUBO problem
    public class CoordinationResultDto
    {
        // Generated by the game; a resent result with the same id is ignored
        public Guid Id { get; set; }

        // Solver variant (or configuration code) the game asked for; with UsedFallback the plan came from the fallback
        public string Variant { get; set; } = "";
        public bool UsedFallback { get; set; }

        // RouteCoverage, CoverAssignment or Flanking
        public string TaskType { get; set; } = "";
        public string? SquadTag { get; set; }
        public string? MapCode { get; set; }
        public int NumAgents { get; set; }
        public int NumNodes { get; set; }
        public int? NumQuboVars { get; set; }
        public double? ObjectiveValue { get; set; }
        public double SolveLatencyMs { get; set; }
        public bool WithinBudget { get; set; }

        // Agent -> route / cover point / flank angle
        public Dictionary<string, object?>? Assignment { get; set; }
        public double? CoordinationScore { get; set; }
        public DateTimeOffset TriggeredAt { get; set; }
    }

    public class SessionUploadResponse
    {
        public ItemCounts Events { get; set; } = new ItemCounts();
        public ItemCounts CoordinationResults { get; set; } = new ItemCounts();
    }

    public class ItemCounts
    {
        public int Accepted { get; set; }

        // Already stored by an earlier upload
        public int Duplicate { get; set; }

        // Invalid item (unknown type, time outside the session, unknown variant...); the rest of the batch is kept
        public int Rejected { get; set; }
    }
}
