// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShadowVale.DAL.Data;

#nullable disable

namespace ShadowVale.DAL.Migrations
{
    [DbContext(typeof(ShadowValeDbContext))]
    partial class ShadowValeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shadowvale")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShadowVale.DAL.Entities.Consumable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<List<string>>("Cures")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cures");

                    b.Property<string>("ExtraEffects")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_effects");

                    b.Property<int>("HealHp")
                        .HasColumnType("integer")
                        .HasColumnName("heal_hp");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("RestoreStamina")
                        .HasColumnType("integer")
                        .HasColumnName("restore_stamina");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("UseTimeSeconds")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("use_time_seconds");

                    b.HasKey("Id")
                        .HasName("pk_consumables");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_consumables_item_id");

                    b.ToTable("consumables", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_consumables_heal_hp", "heal_hp >= 0");

                            t.HasCheckConstraint("ck_consumables_restore_stamina", "restore_stamina >= 0");

                            t.HasCheckConstraint("ck_consumables_use_time", "use_time_seconds >= 0");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.ContentPublicationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("ContentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_version_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_version_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_content_publication_history");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_content_publication_history_actor_id");

                    b.HasIndex("ContentVersionId")
                        .HasDatabaseName("ix_content_publication_history_content_version_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_content_publication_history_created_at");

                    b.HasIndex("PreviousVersionId")
                        .HasDatabaseName("ix_content_publication_history_previous_version_id");

                    b.ToTable("content_publication_history", "shadowvale");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.ContentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid>("AuthoredById")
                        .HasColumnType("uuid")
                        .HasColumnName("authored_by_id");

                    b.Property<string>("Bundle")
                        .HasColumnType("jsonb")
                        .HasColumnName("bundle");

                    b.Property<string>("BundleChecksum")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bundle_checksum");

                    b.Property<string>("Changelog")
                        .HasColumnType("text")
                        .HasColumnName("changelog");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid?>("ParentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_version_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedById")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_id");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_note");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_errors");

                    b.Property<long>("VersionNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("version_no");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("VersionNo"));

                    b.HasKey("Id")
                        .HasName("pk_content_versions");

                    b.HasIndex("AuthoredById")
                        .HasDatabaseName("ix_content_versions_authored_by_id");

                    b.HasIndex("ParentVersionId")
                        .HasDatabaseName("ix_content_versions_parent_version_id");

                    b.HasIndex("PublishedById")
                        .HasDatabaseName("ix_content_versions_published_by_id");

                    b.HasIndex("ReviewedById")
                        .HasDatabaseName("ix_content_versions_reviewed_by_id");

                    b.HasIndex("VersionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_content_versions_version_no");

                    b.HasIndex(new[] { "Status" }, "ix_content_versions_status")
                        .HasDatabaseName("ix_content_versions_status");

                    b.HasIndex(new[] { "Status" }, "ux_content_versions_one_published")
                        .IsUnique()
                        .HasDatabaseName("ux_content_versions_one_published")
                        .HasFilter("status = 'Published'");

                    b.ToTable("content_versions", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_content_versions_published_has_bundle", "status NOT IN ('Published', 'Archived') OR (bundle IS NOT NULL AND bundle_checksum IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.CoordinationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Assignment")
                        .HasColumnType("jsonb")
                        .HasColumnName("assignment");

                    b.Property<double?>("CoordinationScore")
                        .HasColumnType("double precision")
                        .HasColumnName("coordination_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MapCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("map_code");

                    b.Property<int>("NumAgents")
                        .HasColumnType("integer")
                        .HasColumnName("num_agents");

                    b.Property<int>("NumNodes")
                        .HasColumnType("integer")
                        .HasColumnName("num_nodes");

                    b.Property<int?>("NumQuboVars")
                        .HasColumnType("integer")
                        .HasColumnName("num_qubo_vars");

                    b.Property<double?>("ObjectiveValue")
                        .HasColumnType("double precision")
                        .HasColumnName("objective_value");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<double>("SolveLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("solve_latency_ms");

                    b.Property<Guid>("SolverConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("solver_configuration_id");

                    b.Property<string>("SquadTag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("squad_tag");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("task_type");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UsedFallback")
                        .HasColumnType("boolean")
                        .HasColumnName("used_fallback");

                    b.Property<bool>("WithinBudget")
                        .HasColumnType("boolean")
                        .HasColumnName("within_budget");

                    b.HasKey("Id")
                        .HasName("pk_coordination_results");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_coordination_results_session_id");

                    b.HasIndex("SolverConfigurationId")
                        .HasDatabaseName("ix_coordination_results_solver_configuration_id");

                    b.ToTable("coordination_results", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_coordination_results_latency", "solve_latency_ms >= 0");

                            t.HasCheckConstraint("ck_coordination_results_num_agents", "num_agents > 0");

                            t.HasCheckConstraint("ck_coordination_results_num_nodes", "num_nodes > 0");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.CraftingRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("ContentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_version_id");

                    b.Property<decimal>("CraftTimeSeconds")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("craft_time_seconds");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OutputItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_item_id");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("output_quantity");

                    b.Property<Guid?>("RequiredSkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("required_skill_id");

                    b.Property<int>("RequiredSkillLevel")
                        .HasColumnType("integer")
                        .HasColumnName("required_skill_level");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_crafting_recipes");

                    b.HasIndex("OutputItemId")
                        .HasDatabaseName("ix_crafting_recipes_output_item_id");

                    b.HasIndex("RequiredSkillId")
                        .HasDatabaseName("ix_crafting_recipes_required_skill_id");

                    b.HasIndex("ContentVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_crafting_recipes_content_version_id_code");

                    b.ToTable("crafting_recipes", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_crafting_recipes_craft_time", "craft_time_seconds >= 0");

                            t.HasCheckConstraint("ck_crafting_recipes_output_quantity", "output_quantity > 0");

                            t.HasCheckConstraint("ck_crafting_recipes_skill_level", "required_skill_level >= 0");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.CraftingRecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_crafting_recipe_ingredients");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_crafting_recipe_ingredients_item_id");

                    b.HasIndex("RecipeId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_crafting_recipe_ingredients_recipe_id_item_id");

                    b.ToTable("crafting_recipe_ingredients", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_crafting_recipe_ingredients_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.EnemyPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnemyTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("enemy_type_id");

                    b.Property<decimal>("FacingDegrees")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("facing_degrees");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<string>("PatrolRoute")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("patrol_route");

                    b.Property<decimal>("PosX")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("pos_x");

                    b.Property<decimal>("PosY")
                        .HasPrecision(9, 3)
                        .HasColumnType("numeric(9,3)")
                        .HasColumnName("pos_y");

                    b.Property<string>("SpawnCondition")
                        .HasColumnType("jsonb")
                        .HasColumnName("spawn_condition");

                    b.Property<string>("SquadTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("squad_tag");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_enemy_placements");

                    b.HasIndex("EnemyTypeId")
                        .HasDatabaseName("ix_enemy_placements_enemy_type_id");

                    b.HasIndex("MapId")
                        .HasDatabaseName("ix_enemy_placements_map_id");

                    b.ToTable("enemy_placements", "shadowvale");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.EnemyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Accuracy")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("accuracy");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("archetype");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("ContentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_version_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FsmParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("fsm_params");

                    b.Property<decimal>("HearingRange")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("hearing_range");

                    b.Property<bool>("IsBoss")
                        .HasColumnType("boolean")
                        .HasColumnName("is_boss");

                    b.Property<Guid?>("LootTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("loot_table_id");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<decimal>("MoveSpeed")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("move_speed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("VisionAngleDegrees")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vision_angle_degrees");

                    b.Property<decimal>("VisionRange")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("vision_range");

                    b.Property<Guid?>("WeaponId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_id");

                    b.HasKey("Id")
                        .HasName("pk_enemy_types");

                    b.HasIndex("LootTableId")
                        .HasDatabaseName("ix_enemy_types_loot_table_id");

                    b.HasIndex("WeaponId")
                        .HasDatabaseName("ix_enemy_types_weapon_id");

                    b.HasIndex("ContentVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_enemy_types_content_version_id_code");

                    b.ToTable("enemy_types", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_enemy_types_accuracy", "accuracy BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_enemy_types_max_hp", "max_hp > 0");

                            t.HasCheckConstraint("ck_enemy_types_move_speed", "move_speed > 0");

                            t.HasCheckConstraint("ck_enemy_types_vision_angle", "vision_angle_degrees BETWEEN 0 AND 360");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_version");

                    b.Property<Guid?>("ContentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_version_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("MapCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("map_code");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("outcome");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid?>("SolverConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("solver_configuration_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("human")
                        .HasColumnName("source");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_game_sessions");

                    b.HasIndex("ContentVersionId")
                        .HasDatabaseName("ix_game_sessions_content_version_id");

                    b.HasIndex("MapCode")
                        .HasDatabaseName("ix_game_sessions_map_code");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_game_sessions_player_id");

                    b.HasIndex("SolverConfigurationId")
                        .HasDatabaseName("ix_game_sessions_solver_configuration_id");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_game_sessions_source");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_game_sessions_started_at");

                    b.ToTable("game_sessions", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_game_sessions_ended_after_started", "ended_at IS NULL OR ended_at >= started_at");

                            t.HasCheckConstraint("ck_game_sessions_source", "source IN ('human', 'replay')");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseValue")
                        .HasColumnType("integer")
                        .HasColumnName("base_value");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("ContentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_version_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("IconKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("icon_key");

                    b.Property<int>("MaxStack")
                        .HasColumnType("integer")
                        .HasColumnName("max_stack");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rarity");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("ContentVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_items_content_version_id_code");

                    b.ToTable("items", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_items_base_value", "base_value >= 0");

                            t.HasCheckConstraint("ck_items_max_stack", "max_stack >= 1");

                            t.HasCheckConstraint("ck_items_weapon_not_stackable", "type <> 'Weapon' OR max_stack = 1");

                            t.HasCheckConstraint("ck_items_weight", "weight >= 0");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.LootTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("ContentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_version_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("RollsMax")
                        .HasColumnType("integer")
                        .HasColumnName("rolls_max");

                    b.Property<int>("RollsMin")
                        .HasColumnType("integer")
                        .HasColumnName("rolls_min");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_loot_tables");

                    b.HasIndex("ContentVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_loot_tables_content_version_id_code");

                    b.ToTable("loot_tables", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_loot_tables_rolls_min", "rolls_min >= 0");

                            t.HasCheckConstraint("ck_loot_tables_rolls_range", "rolls_max >= rolls_min");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.LootTableEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("loot_table_id");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("max_quantity");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("min_quantity");

                    b.Property<short>("Tier")
                        .HasColumnType("smallint")
                        .HasColumnName("tier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_loot_table_entries");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_loot_table_entries_item_id");

                    b.HasIndex("LootTableId", "ItemId", "Tier")
                        .IsUnique()
                        .HasDatabaseName("ix_loot_table_entries_loot_table_id_item_id_tier");

                    b.ToTable("loot_table_entries", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_loot_table_entries_quantity", "min_quantity >= 1 AND max_quantity >= min_quantity");

                            t.HasCheckConstraint("ck_loot_table_entries_tier", "tier BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_loot_table_entries_weight", "weight > 0");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("ContentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_version_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSafeCamp")
                        .HasColumnType("boolean")
                        .HasColumnName("is_safe_camp");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layout");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NavGraph")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("nav_graph");

                    b.Property<string>("SceneKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scene_key");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_maps");

                    b.HasIndex("ContentVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_maps_content_version_id_code");

                    b.ToTable("maps", "shadowvale");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.MapLootTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContainerTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("container_tag");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("loot_table_id");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_map_loot_tables");

                    b.HasIndex("LootTableId")
                        .HasDatabaseName("ix_map_loot_tables_loot_table_id");

                    b.HasIndex("MapId", "LootTableId", "ContainerTag")
                        .IsUnique()
                        .HasDatabaseName("ix_map_loot_tables_map_id_loot_table_id_container_tag");

                    b.ToTable("map_loot_tables", "shadowvale");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("InstallId")
                        .IsUnique()
                        .HasDatabaseName("ix_players_install_id");

                    b.ToTable("players", "shadowvale");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("ContentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_version_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("objectives");

                    b.PrimitiveCollection<List<string>>("Prerequisites")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("prerequisites");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer")
                        .HasColumnName("reward_xp");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quests");

                    b.HasIndex("ContentVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_quests_content_version_id_code");

                    b.ToTable("quests", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_quests_reward_xp", "reward_xp >= 0");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.QuestReward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quest_rewards");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_quest_rewards_item_id");

                    b.HasIndex("QuestId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_quest_rewards_quest_id_item_id");

                    b.ToTable("quest_rewards", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_quest_rewards_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "shadowvale");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("ContentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_version_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Effects")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("effects");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer")
                        .HasColumnName("max_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("XpCurve")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("xp_curve");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("ContentVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_content_version_id_code");

                    b.ToTable("skills", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_skills_max_level", "max_level > 0");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.SolverConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("algorithm");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("family");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Library")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("library");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("params");

                    b.Property<string>("QuboWeights")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("qubo_weights");

                    b.Property<int>("TimeBudgetMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_budget_ms");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_solver_configurations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_solver_configurations_code");

                    b.ToTable("solver_configurations", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_solver_configurations_family", "(family = 'Classical') = (algorithm IN ('Greedy', 'Genetic', 'ClassicalSa')) AND (family = 'QuantumHardware') = (algorithm = 'QpuDwave')");

                            t.HasCheckConstraint("ck_solver_configurations_time_budget", "time_budget_ms > 0");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.TelemetryEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("MapCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("map_code");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<float?>("PosX")
                        .HasColumnType("real")
                        .HasColumnName("pos_x");

                    b.Property<float?>("PosY")
                        .HasColumnType("real")
                        .HasColumnName("pos_y");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_telemetry_events");

                    b.HasIndex("MapCode")
                        .HasDatabaseName("ix_telemetry_events_map_code")
                        .HasFilter("map_code IS NOT NULL");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_telemetry_events_occurred_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OccurredAt"), "brin");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("ix_telemetry_events_event_type_occurred_at");

                    b.HasIndex("SessionId", "ClientEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_telemetry_events_session_id_client_event_id");

                    b.ToTable("telemetry_events", "shadowvale");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", "shadowvale");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AmmoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("ammo_item_id");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("class");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Damage")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("damage");

                    b.Property<decimal>("DurabilityPerUse")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("durability_per_use");

                    b.Property<decimal>("EffectiveRange")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("effective_range");

                    b.Property<decimal>("FireRate")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("fire_rate");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suppressed");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int?>("MagazineSize")
                        .HasColumnType("integer")
                        .HasColumnName("magazine_size");

                    b.Property<int>("MaxDurability")
                        .HasColumnType("integer")
                        .HasColumnName("max_durability");

                    b.Property<decimal>("NoiseRadius")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("noise_radius");

                    b.Property<decimal?>("ReloadTimeSeconds")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("reload_time_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_weapons");

                    b.HasIndex("AmmoItemId")
                        .HasDatabaseName("ix_weapons_ammo_item_id");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_weapons_item_id");

                    b.ToTable("weapons", "shadowvale", t =>
                        {
                            t.HasCheckConstraint("ck_weapons_damage", "damage > 0");

                            t.HasCheckConstraint("ck_weapons_effective_range", "effective_range >= 0");

                            t.HasCheckConstraint("ck_weapons_fire_rate", "fire_rate > 0");

                            t.HasCheckConstraint("ck_weapons_magazine_size", "magazine_size IS NULL OR magazine_size >= 1");

                            t.HasCheckConstraint("ck_weapons_max_durability", "max_durability > 0");

                            t.HasCheckConstraint("ck_weapons_melee_no_ammo", "class <> 'Melee' OR (ammo_item_id IS NULL AND magazine_size IS NULL)");

                            t.HasCheckConstraint("ck_weapons_noise_radius", "noise_radius >= 0");
                        });
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Consumable", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.Item", "Item")
                        .WithOne("Consumable")
                        .HasForeignKey("ShadowVale.DAL.Entities.Consumable", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumables_items_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.ContentPublicationHistory", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_content_publication_history_users_actor_id");

                    b.HasOne("ShadowVale.DAL.Entities.ContentVersion", "ContentVersion")
                        .WithMany()
                        .HasForeignKey("ContentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_publication_history_content_versions_content_versio");

                    b.HasOne("ShadowVale.DAL.Entities.ContentVersion", "PreviousVersion")
                        .WithMany()
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_content_publication_history_content_versions_previous_versi");

                    b.Navigation("Actor");

                    b.Navigation("ContentVersion");

                    b.Navigation("PreviousVersion");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.ContentVersion", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.User", "AuthoredBy")
                        .WithMany()
                        .HasForeignKey("AuthoredById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_versions_users_authored_by_id");

                    b.HasOne("ShadowVale.DAL.Entities.ContentVersion", "ParentVersion")
                        .WithMany()
                        .HasForeignKey("ParentVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_content_versions_content_versions_parent_version_id");

                    b.HasOne("ShadowVale.DAL.Entities.User", "PublishedBy")
                        .WithMany()
                        .HasForeignKey("PublishedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_content_versions_users_published_by_id");

                    b.HasOne("ShadowVale.DAL.Entities.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_content_versions_users_reviewed_by_id");

                    b.Navigation("AuthoredBy");

                    b.Navigation("ParentVersion");

                    b.Navigation("PublishedBy");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.CoordinationResult", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.GameSession", "Session")
                        .WithMany("CoordinationResults")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coordination_results_game_sessions_session_id");

                    b.HasOne("ShadowVale.DAL.Entities.SolverConfiguration", "SolverConfiguration")
                        .WithMany()
                        .HasForeignKey("SolverConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coordination_results_solver_configurations_solver_configura");

                    b.Navigation("Session");

                    b.Navigation("SolverConfiguration");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.CraftingRecipe", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.ContentVersion", "ContentVersion")
                        .WithMany("CraftingRecipes")
                        .HasForeignKey("ContentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crafting_recipes_content_versions_content_version_id");

                    b.HasOne("ShadowVale.DAL.Entities.Item", "OutputItem")
                        .WithMany()
                        .HasForeignKey("OutputItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crafting_recipes_items_output_item_id");

                    b.HasOne("ShadowVale.DAL.Entities.Skill", "RequiredSkill")
                        .WithMany()
                        .HasForeignKey("RequiredSkillId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_crafting_recipes_skills_required_skill_id");

                    b.Navigation("ContentVersion");

                    b.Navigation("OutputItem");

                    b.Navigation("RequiredSkill");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.CraftingRecipeIngredient", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crafting_recipe_ingredients_items_item_id");

                    b.HasOne("ShadowVale.DAL.Entities.CraftingRecipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crafting_recipe_ingredients_crafting_recipes_recipe_id");

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.EnemyPlacement", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.EnemyType", "EnemyType")
                        .WithMany()
                        .HasForeignKey("EnemyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_placements_enemy_types_enemy_type_id");

                    b.HasOne("ShadowVale.DAL.Entities.Map", "Map")
                        .WithMany("EnemyPlacements")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_placements_maps_map_id");

                    b.Navigation("EnemyType");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.EnemyType", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.ContentVersion", "ContentVersion")
                        .WithMany("EnemyTypes")
                        .HasForeignKey("ContentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enemy_types_content_versions_content_version_id");

                    b.HasOne("ShadowVale.DAL.Entities.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_enemy_types_loot_tables_loot_table_id");

                    b.HasOne("ShadowVale.DAL.Entities.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_enemy_types_weapons_weapon_id");

                    b.Navigation("ContentVersion");

                    b.Navigation("LootTable");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.GameSession", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.ContentVersion", "ContentVersion")
                        .WithMany()
                        .HasForeignKey("ContentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_game_sessions_content_versions_content_version_id");

                    b.HasOne("ShadowVale.DAL.Entities.Player", "Player")
                        .WithMany("Sessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_game_sessions_players_player_id");

                    b.HasOne("ShadowVale.DAL.Entities.SolverConfiguration", "SolverConfiguration")
                        .WithMany()
                        .HasForeignKey("SolverConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_game_sessions_solver_configurations_solver_configuration_id");

                    b.Navigation("ContentVersion");

                    b.Navigation("Player");

                    b.Navigation("SolverConfiguration");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Item", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.ContentVersion", "ContentVersion")
                        .WithMany("Items")
                        .HasForeignKey("ContentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_content_versions_content_version_id");

                    b.Navigation("ContentVersion");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.LootTable", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.ContentVersion", "ContentVersion")
                        .WithMany("LootTables")
                        .HasForeignKey("ContentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loot_tables_content_versions_content_version_id");

                    b.Navigation("ContentVersion");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.LootTableEntry", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loot_table_entries_items_item_id");

                    b.HasOne("ShadowVale.DAL.Entities.LootTable", "LootTable")
                        .WithMany("Entries")
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loot_table_entries_loot_tables_loot_table_id");

                    b.Navigation("Item");

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Map", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.ContentVersion", "ContentVersion")
                        .WithMany("Maps")
                        .HasForeignKey("ContentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maps_content_versions_content_version_id");

                    b.Navigation("ContentVersion");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.MapLootTable", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_loot_tables_loot_tables_loot_table_id");

                    b.HasOne("ShadowVale.DAL.Entities.Map", "Map")
                        .WithMany("LootTables")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_map_loot_tables_maps_map_id");

                    b.Navigation("LootTable");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Quest", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.ContentVersion", "ContentVersion")
                        .WithMany("Quests")
                        .HasForeignKey("ContentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quests_content_versions_content_version_id");

                    b.Navigation("ContentVersion");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.QuestReward", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quest_rewards_items_item_id");

                    b.HasOne("ShadowVale.DAL.Entities.Quest", "Quest")
                        .WithMany("Rewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quest_rewards_quests_quest_id");

                    b.Navigation("Item");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Skill", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.ContentVersion", "ContentVersion")
                        .WithMany("Skills")
                        .HasForeignKey("ContentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skills_content_versions_content_version_id");

                    b.Navigation("ContentVersion");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.TelemetryEvent", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.GameSession", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telemetry_events_game_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Weapon", b =>
                {
                    b.HasOne("ShadowVale.DAL.Entities.Item", "AmmoItem")
                        .WithMany()
                        .HasForeignKey("AmmoItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_weapons_items_ammo_item_id");

                    b.HasOne("ShadowVale.DAL.Entities.Item", "Item")
                        .WithOne("Weapon")
                        .HasForeignKey("ShadowVale.DAL.Entities.Weapon", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weapons_items_item_id");

                    b.Navigation("AmmoItem");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.ContentVersion", b =>
                {
                    b.Navigation("CraftingRecipes");

                    b.Navigation("EnemyTypes");

                    b.Navigation("Items");

                    b.Navigation("LootTables");

                    b.Navigation("Maps");

                    b.Navigation("Quests");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.CraftingRecipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.GameSession", b =>
                {
                    b.Navigation("CoordinationResults");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Item", b =>
                {
                    b.Navigation("Consumable");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.LootTable", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Map", b =>
                {
                    b.Navigation("EnemyPlacements");

                    b.Navigation("LootTables");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Player", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.Quest", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("ShadowVale.DAL.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
