namespace ShadowVale.DAL.Entities;

// One snapshot of all game content. The game downloads Bundle of the single Published version.
public class ContentVersion : BaseEntity
{
    // 1, 2, 3... shown in the UI; generated by the database
    public long VersionNo { get; set; }
    public string Label { get; set; } = null!;
    public string? Changelog { get; set; }

    // Version this one was cloned from, for compare
    public Guid? ParentVersionId { get; set; }
    public ContentVersion? ParentVersion { get; set; }

    public ContentStatus Status { get; set; } = ContentStatus.Draft;

    // Bumped on every content change; EF concurrency token, so two editors cannot overwrite each other
    public long Revision { get; set; }

    public string SchemaVersion { get; set; } = "1.0";

    // Built JSON bundle (jsonb) and its SHA-256, set when the version is validated for publishing
    public string? Bundle { get; set; }
    public string? BundleChecksum { get; set; }
    public string? ValidationErrors { get; set; }
    public DateTime? ValidatedAt { get; set; }

    public Guid AuthoredById { get; set; }
    public User AuthoredBy { get; set; } = null!;
    public DateTime? SubmittedAt { get; set; }

    public Guid? ReviewedById { get; set; }
    public User? ReviewedBy { get; set; }
    public DateTime? ReviewedAt { get; set; }
    public string? ReviewNote { get; set; }

    public Guid? PublishedById { get; set; }
    public User? PublishedBy { get; set; }
    public DateTime? PublishedAt { get; set; }
    public DateTime? ArchivedAt { get; set; }

    public ICollection<Item> Items { get; set; } = [];
    public ICollection<Skill> Skills { get; set; } = [];
    public ICollection<LootTable> LootTables { get; set; } = [];
    public ICollection<EnemyType> EnemyTypes { get; set; } = [];
    public ICollection<Map> Maps { get; set; } = [];
    public ICollection<CraftingRecipe> CraftingRecipes { get; set; } = [];
    public ICollection<Quest> Quests { get; set; } = [];
}
