namespace ShadowVale.DAL.Entities;

// One play session, uploaded in a batch at session end. Id is generated by the game so a retried upload
// is recognised; CreatedAt is when the server received it.
public class GameSession : BaseEntity
{
    public Guid? PlayerId { get; set; }
    public Player? Player { get; set; }

    // Content the session was played with, so dashboards compare per version
    public Guid ContentVersionId { get; set; }
    public ContentVersion ContentVersion { get; set; } = null!;

    public DateTime StartedAt { get; set; }
    public DateTime? EndedAt { get; set; }
    public SessionOutcome Outcome { get; set; } = SessionOutcome.InProgress;
    public string? ClientVersion { get; set; }
    public string Platform { get; set; } = "windows";

    public ICollection<TelemetryEvent> Events { get; set; } = [];
    public ICollection<CoordinationResult> CoordinationResults { get; set; } = [];
}
