namespace ShadowVale.DAL.Entities;

// One play session. The game registers it when play starts (and gets its solver), then uploads the batch at the end.
// Id is generated by the game so a retried upload is recognised; CreatedAt is when the server first saw it.
public class GameSession : BaseEntity
{
    public Guid? PlayerId { get; set; }
    public Player? Player { get; set; }

    // Content the session was played with, so dashboards compare per version.
    // Null when the game ran on its built-in fallback bundle or sent a version this server does not know.
    public Guid? ContentVersionId { get; set; }
    public ContentVersion? ContentVersion { get; set; }

    // Solver the server assigned to the session (A/B arm, or the variant the replay harness asked for).
    // Null when no solver was assigned: the session is left out of the solver comparison.
    public Guid? SolverConfigurationId { get; set; }
    public SolverConfiguration? SolverConfiguration { get; set; }

    public SessionSource Source { get; set; } = SessionSource.Human;
    public string? MapCode { get; set; }

    public DateTime StartedAt { get; set; }
    public DateTime? EndedAt { get; set; }
    public SessionOutcome Outcome { get; set; } = SessionOutcome.InProgress;
    public string? ClientVersion { get; set; }
    public string Platform { get; set; } = "windows";

    // Full counters and the encounter list counted by the game (jsonb, shape: Contracts SessionStats).
    // Kept here because events are throttled and capped, so counting events would undercount.
    public string Stats { get; set; } = "{}";

    public ICollection<TelemetryEvent> Events { get; set; } = [];
    public ICollection<CoordinationResult> CoordinationResults { get; set; } = [];
}
