namespace ShadowVale.DAL.Entities;

// Largest table, so a bigint identity key instead of BaseEntity's Guid
public class TelemetryEvent
{
    public long Id { get; set; }

    public Guid SessionId { get; set; }
    public GameSession Session { get; set; } = null!;

    // Generated by the game; (SessionId, ClientEventId) is unique so a retried batch does not duplicate events
    public Guid ClientEventId { get; set; }

    // map_enter / map_exit / shot_fired / player_detected / takedown / item_crafted / death...
    public string EventType { get; set; } = null!;

    // Map of the session's content version (heat maps, mission funnels)
    public string? MapCode { get; set; }
    public float? PosX { get; set; }
    public float? PosY { get; set; }
    public DateTime OccurredAt { get; set; }

    // Event-specific data, e.g. {"weapon": "rifle_ak"} (jsonb)
    public string Payload { get; set; } = "{}";
    public DateTime ReceivedAt { get; set; }
}
